name: CI/CD
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/chekout@v2

      - name: build
        run: |
          echo "building the application"

test:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run: |
        echo "running test..."

deploy:
  run-on: ubuntu-latest
  needs: test
  step:
    - name: Checkout code
      uses: action /checkout!v2

    - name: Deploy
      run: |
        echo "Deploy the application..."
